# Generated by Django 5.1.7 on 2025-03-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getmoestate', '0002_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='created_at',
        ),
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='name',
            field=models.CharField(default='Default Name', max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.CharField(default='N/A', max_length=15),
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
